# NumPy Introduction

In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3, 4, 5, 6]
x = np.array(mylist)

In [3]:
x

array([1, 2, 3, 4, 5, 6])

In [4]:
mylist = [3, 4, 5, 6, 7, 8]
y = np.array(mylist)
y

array([3, 4, 5, 6, 7, 8])

In [5]:
z = np.array([[1, 2, 3, 4, 5, 6], [4, 5, 6, 4, 5, 6]])
print(z)

[[1 2 3 4 5 6]
 [4 5 6 4 5 6]]


In [6]:
np.shape(z)

(2, 6)

In [7]:
a = np.arange(0, 1000, 10)
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250,
       260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380,
       390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510,
       520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640,
       650, 660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770,
       780, 790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900,
       910, 920, 930, 940, 950, 960, 970, 980, 990])

In [8]:
a = a.reshape(25, 4)

In [9]:
a

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110],
       [120, 130, 140, 150],
       [160, 170, 180, 190],
       [200, 210, 220, 230],
       [240, 250, 260, 270],
       [280, 290, 300, 310],
       [320, 330, 340, 350],
       [360, 370, 380, 390],
       [400, 410, 420, 430],
       [440, 450, 460, 470],
       [480, 490, 500, 510],
       [520, 530, 540, 550],
       [560, 570, 580, 590],
       [600, 610, 620, 630],
       [640, 650, 660, 670],
       [680, 690, 700, 710],
       [720, 730, 740, 750],
       [760, 770, 780, 790],
       [800, 810, 820, 830],
       [840, 850, 860, 870],
       [880, 890, 900, 910],
       [920, 930, 940, 950],
       [960, 970, 980, 990]])

In [10]:
o = np.linspace(0, 999, 100)
o

array([  0.        ,  10.09090909,  20.18181818,  30.27272727,
        40.36363636,  50.45454545,  60.54545455,  70.63636364,
        80.72727273,  90.81818182, 100.90909091, 111.        ,
       121.09090909, 131.18181818, 141.27272727, 151.36363636,
       161.45454545, 171.54545455, 181.63636364, 191.72727273,
       201.81818182, 211.90909091, 222.        , 232.09090909,
       242.18181818, 252.27272727, 262.36363636, 272.45454545,
       282.54545455, 292.63636364, 302.72727273, 312.81818182,
       322.90909091, 333.        , 343.09090909, 353.18181818,
       363.27272727, 373.36363636, 383.45454545, 393.54545455,
       403.63636364, 413.72727273, 423.81818182, 433.90909091,
       444.        , 454.09090909, 464.18181818, 474.27272727,
       484.36363636, 494.45454545, 504.54545455, 514.63636364,
       524.72727273, 534.81818182, 544.90909091, 555.        ,
       565.09090909, 575.18181818, 585.27272727, 595.36363636,
       605.45454545, 615.54545455, 625.63636364, 635.72

In [11]:
np.shape(o)

(100,)

In [12]:
o.resize(10, 10)

In [13]:
o

array([[  0.        ,  10.09090909,  20.18181818,  30.27272727,
         40.36363636,  50.45454545,  60.54545455,  70.63636364,
         80.72727273,  90.81818182],
       [100.90909091, 111.        , 121.09090909, 131.18181818,
        141.27272727, 151.36363636, 161.45454545, 171.54545455,
        181.63636364, 191.72727273],
       [201.81818182, 211.90909091, 222.        , 232.09090909,
        242.18181818, 252.27272727, 262.36363636, 272.45454545,
        282.54545455, 292.63636364],
       [302.72727273, 312.81818182, 322.90909091, 333.        ,
        343.09090909, 353.18181818, 363.27272727, 373.36363636,
        383.45454545, 393.54545455],
       [403.63636364, 413.72727273, 423.81818182, 433.90909091,
        444.        , 454.09090909, 464.18181818, 474.27272727,
        484.36363636, 494.45454545],
       [504.54545455, 514.63636364, 524.72727273, 534.81818182,
        544.90909091, 555.        , 565.09090909, 575.18181818,
        585.27272727, 595.36363636],
       [60

In [14]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# Pandas

In [15]:
import pandas as pd

In [16]:
pd.Series?

In [17]:
animals = ['Tiger', 'Lion', 'Bear', 'Chimpanzee']

In [18]:
pd.Series(animals)

0         Tiger
1          Lion
2          Bear
3    Chimpanzee
dtype: object

In [19]:
numbers = [1, 2, 3, 4, 5]
pd.Series(numbers)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [20]:
np.nan == None

False

In [21]:
np.isnan(np.nan)

True

# READING MULTIPLE FILES INTO ONE DATAFRAME

In [36]:
import pandas as dd

df = dd.read_csv('U*.TXT', delimiter=' ', names=['X', 'Y', 'TS', 'T', 'AZ', 'AL', 'P'], header=None, skiprows=1)

FileNotFoundError: [Errno 2] File b'U*.TXT' does not exist: b'U*.TXT'

In [35]:
print(df.tail(180))

        X     Y        TS  T    AZ   AL    P
121  5747  4077  17614284  1  1360  550  405
122  5802  3975  17614294  1  1380  550  443
123  5847  3855  17614304  1  1390  550  477
124  5862  3705  17614314  1  1390  550  501
125  5862  3546  17614324  1  1390  550  513
126  5830  3380  17614334  1  1390  550  515
127  5767  3168  17614344  1  1390  550  515
128  5682  2991  17614354  1  1390  550  499
129  5608  2837  17614364  1  1390  550  404
130  5559  2743  17614374  1  1380  550   56
131  5490  3069  17614454  0  1360  560  279
132  5569  3052  17614464  1  1360  560  337
133  5589  3044  17614474  1  1350  550  343
134  5599  3038  17614484  1  1350  550  387
135  5663  3014  17614494  1  1350  550  448
136  5760  2981  17614504  1  1350  550  519
137  5879  2927  17614514  1  1350  550  586
138  6023  2867  17614524  1  1350  550  611
139  6224  2790  17614534  1  1350  550  619
140  6464  2704  17614544  1  1350  550  563
141  6745  2636  17614554  1  1350  570  329
142  6962 